// <auto-generated />
using System;
using LoginApp.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoginApp.Migrations
{
    [DbContext(typeof(ContextoLogin))]
    partial class ContextoLoginModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LoginApp.Infraestructura.Modelos.CuentasCorreo", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("varchar(900)")
                        .IsUnicode(false);

                    b.Property<string>("AccesToken")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("ExcepcionAutenticacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiracionAccesToken")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiracionRefreshToken")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("Scope")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.HasKey("Email");

                    b.ToTable("CuentasCorreo");
                });
#pragma warning restore 612, 618
        }
    }
}
